
platform :ios, '8.0'

use_frameworks!

def pods
    pod 'Kingfisher', '~> 3.0'
    pod 'RDVTabBarController'
    pod 'ReachabilitySwift', '~> 3'
    pod 'Kanna', '~> 2.1.0'
    pod 'Alamofire', '~> 4.4'
    pod 'AlgoliaSearch-Client-Swift', '~> 4.0’
    pod 'RxSwift', '3.6.1'
    pod 'RxCocoa', '3.6.1'
    pod 'RxDataSources', '1.0.4'
end


target ‘DouBanMovie’ do
    pods
end